Rplus/Pokemon-shiny

index.html
l10n.js
manifest.json
sw.js

Removed scsss that's not reachable in sw.js

---

assets/pms.json

https://mobile.twitter.com/pokexperto/status/1313577212281532417

Added Ferroseed family release date

---

assets/pms.json

https://pokemongolive.com/en/post/halloween2020/

Spiritbomb release date

---

assets/pms.json

Add the release dates of the shinies based on https://www.p337.info/pokemongo/pages/shiny-release-dates/
Resolves #45

Add release dates

---

assets/pms.json

Not sure if that "isotope" is necessary here, it may be used for grouping somehow

Add Mega Absol

---

assets/pms.json

add Scraggy family for issue: https://github.com/Rplus/Pokemon-shiny/issues/228

Pm559.s.icon.png & pm560.s.icon.png

---

assets/pms.json

this is my first attempt to create a Pull Request with changes directly in the pms.json file--please check it carefully!
this Pull Request addresses:
https://github.com/Rplus/Pokemon-shiny/issues/225

Update pms.json: add pm25.fWCS_2023.s.icon.png

---

assets/pms.json

I had October for release dates but should be September

Fix release dates

---

assets/pms.json

Eevee with Safari Hat (but not the evolutions) has Style settings like Eevee w Cherry Blossoms--not sure if this is required!

Update pms.json: add Eevee family w Safari Hat

---

assets/pms.json

not confident I have the isotope and family values correct :-(

Update pms.json: add Detective Pikachu family

---

assets/pms.json

my attempt to add Slowpoke w Cowboy Hat (new family, new isotope, offset style)

Update pms.json: add Slowpoke w Cowboy Hat

---

assets/pms.json

not sure I'm doing this right. I've created an isotope for these two but kept them part of wooper family

Update pms.json: add Paldean Wooper family

---

assets/pms.json

adding costume Dragonite and costume Wooper family. Hope I did it correctly--trying to make costume Wooper family a new group in the list.

Update pms.json: add Fashion Week 2023

---

assets/pms.json

Add cottonee w flower crown family

---

assets/pms.json

Update pms.json: add Celesteela & Kartana

---

assets/pms.json

Update pms.json: add Top Hat suffix to costume Pumpkaboo family

---

assets/pms.json

add Sandile family per "World of Wonders: Taken Over!" event. closes #358

Update pms.json: add Sandile family

---

assets/pms.json

Update pms.json: add Go Fest 2024

---

assets/pms.json

Update pms.json: add Bounsweet family

---

assets/pms.json

Update pms.json: separate costume etc. families

---

assets/pms.json

Update pms.json: add Mareanie family

---

assets/pms.json

Update pms.json: add Necrozma variant forms

---

assets/pms.json

Update pms.json: add more GO Fest 2024 mons

---

assets/pms.json

Update pms.json: fix crabrawler fam release date

---

assets/pms.json

Update pms.json: add Larvesta family

---

assets/pms.json

Update pms.json: add Slakoth w Visor family

---

assets/pms.json

I think this addresses comment: https://github.com/Rplus/Pokemon-shiny/issues/377#issuecomment-2156772863
I added an isotope parameter

Update pms.json: fix Slakoth w Visor

---

assets/pms.json

Update pms.json: add Tynamo family

---

assets/pms.json

Update pms.json: add Grimer family w Party Hat

---

assets/pms.json

a new event released Jangmo-O family earlier

Update pms.json: fix Jangmo-O release date (new egg event)

---

assets/pms.json

Update pms.json: add Popplio family

---

assets/pms.json

Update pms.json: add Pikachu World Championships 2024

---

assets/pms.json

Update pms.json: fix Mienshao image

---

assets/pms.json

Update pms.json: add Skwovet & Wooloo fams

---

assets/pms.json

Update pms.json: add Passimian

---

assets/pms.json

Update pms.json: add Sewaddle family

---

assets/pms.json

Doing this on mobile device. Really hard! Hope I did it right. 
Closes #405 and #409

Add zacian and Zamazenta

---

assets/pms.json

closes #418 
I've added the Style formatting used for other Megas, not sure how well it will work for this one

Update pms.json: add Mega Mawile

---

assets/pms.json

already added Wild Area Snorlax via PR #421 
this closes #420

Update pms.json: add Pop Star and Rock Star chus

---

assets/pms.json

Add Toxel family, add Wild Area Snorlax, remove some duplicate entries

---

assets/pms.json

Update pms.json: add Smoliv family

---

assets/pms.json

Add gigantimax mons w fixed release dates

---

assets/pms.json

Update pms.json: add Rowlet & Froakie familes w costume

---

assets/pms.json

Update pms.json: add Pikachu w Saree

---

assets/pms.json

Update pms.json: add G Corsola and Cursola

---

assets/pms.json

Update pms.json: fix Snorlax w Jacket fn

---

assets/pms.json

Update pms.json: fix Pika release dates

---

assets/pms.json

Update pms.json: add Genesect Chill Drive

---

assets/pms.json

I added type = _31 to try to fix G Corsola being auto-registered

Update pms.json: fix G Corsola reg'd

---

assets/pms.json

Update pms.json: add Gigantimax Lapras

---

assets/pms.json

Update pms.json: add red & blue striped Basculin

---

assets/pms.json

Update pms.json: add costume Wooloo and Cetoddle families

---

assets/pms.json

Update pms.json: add-Dedenne-w-holiday-attire-and-Sandygast-family

---

assets/pms.json

Update pms.json: add Sprigatito family

---

assets/pms.json

Update pms.json: add Mega Gallade

---

assets/pms.json

Update pms.json: add Minccino family w costume

---

assets/pms.json

Update pms.json: add 2025 GO Tour Chus

---

assets/pms.json

Update pms.json: add B & W Kyurem

---

assets/pms.json

This change resolves #464 by adding the asset for shiny Gigantamax Kingler.

Add Gigantamax Kingler

---

assets/pms.json

Update pms.json: add Nymble family

---

assets/pms.json

Update pms.json: add Scatterbug family

---

assets/pms.json

Update pms.json: fix Nymble

---

assets/pms.json

Update pms.json: add Fuecoco family

---

assets/pms.json

Update pms.json: add Bruxish

---

assets/pms.json

Update pms.json: add Charcadet family

---

assets/pms.json

Update pms.json: add Mega Audino

---

assets/pms.json

Update pms.json: add Stakataka & Blacephalon

---

assets/pms.json

Update pms.json: add Floragato w hat

---

assets/pms.json

Add gigantimax snorlax

---

assets/pms.json

Update pms.json: add Rookidee family

---

assets/pms.json

Update pms.json: add Tandemaus family

---

assets/pms.json

Update pms.json: add Salandit family

---

assets/pms.json

Pokemon go fest 2025

---

assets/pms.json

Update pms.json: add Pika; Indonesian & WC25
